#include <iostream>
#include <string.h>
#include <set>
#include <string>
#include <stdio.h>

int allcommon(const char *t1, const char *t2)
{
	std::set<std::string> s;
	int t1l=strlen(t1);
	int t2l=strlen(t2);
	int i; //indeks rozpoczynajacy porownanie
	int l; //dlugosc porownywanego ciagu
	int p; //pozycja w drugim ciagu do przyrownywania
	for(i=0; i<t1l; ++i)
		for(p=0; p<t2l; ++p)
			for(l=1; l<=t1l; ++l)
			{
				int cmpres=strncmp(t1+i, t2+p, l);
				if (cmpres==0)
				{
					s.insert(std::string(t1+i, l));
					std::cout<<std::string(t1+i, l)<<std::endl;
				}
				else
				{
					break;
				}
			}
	return s.size();
}

int main(int, char*[])
{
	const char* t1="QnVpbGRpbmcgbGVhZGVycyBvZiB0aGUgZGlnaXRhbCB3b3JsZA0KV2l0aCBhYm91dCAxOCAwMDAg\
ZXhwZXJ0cywgVGlldG8gaXMgdGhlIGxlYWRpbmcgSVQgc2VydmljZQ0KY29tcGFueSBpbiBOb3J0\
aGVybiBFdXJvcGUgcHJvdmlkaW5nIElUIGFuZCBwcm9kdWN0DQplbmdpbmVlcmluZyBzZXJ2aWNl\
cy4NCk91ciBzcGVjaWFsaXplZCBJVCBzb2x1dGlvbnMgYW5kIHNlcnZpY2VzIGNvbXBsZW1lbnRl\
ZCBieQ0KYSBzdHJvbmcgdGVjaG5vbG9neSBwbGF0Zm9ybSBjcmVhdGUgdGFuZ2libGUgYnVzaW5l\
c3MgYmVuZWZpdHMuDQpBcyBhIHRydXN0ZWQgdHJhbnNmb3JtYXRpb24gcGFydG5lciwgd2UgYXJl\
IGNsb3NlIHRvIG91cg0KY3VzdG9tZXJzIGFuZCB1bmRlcnN0YW5kIHRoZWlyIHVuaXF1ZSBuZWVk\
cy4NCk91ciBidXNpbmVzcyBsaW5lcyBhcmUgdGhlIGZvbGxvd2luZzoNCmwgSW5kdXN0cnkgc29s\
dXRpb25zIHN1cHBvcnQgY3VzdG9tZXJzIGJ1c2luZXNzDQpwcm9jZXNzZXMgYXMgd2VsbCBhcyBo\
ZWxwIHRoZW0gbWFuYWdlIGVuZC1jdXN0b21lcg0KaW50ZXJmYWNlIGFuZCBjcmVhdGUgZ3JlYXQg\
c2VydmljZSBleHBlcmllbmNlcy4gSW4gdGhpcw0KY2F0ZWdvcnksIHdlIHByb3ZpZGUgc29sdXRp\
b25zIHRvIGluZHVzdHJ5LXNwZWNpZmljIG5lZWRzLg0KVGhlc2Ugc29sdXRpb25zIGFyZSBvZnRl\
biBiYXNlZCBvbiBwcm9kdWN0cyBkZXZlbG9wZWQNCmJ5IFRpZXRvLiBPbiB0b3Agb2YgdGhlc2Us\
IHdlIG9mZmVyIGluZHVzdHJ5IGNvbnN1bHRpbmcgYW5kDQpjdXN0b21lci1zcGVjaWZpYyBpbnRl\
Z3JhdGlvbiB3b3JrLg0KbCBFbnRlcnByaXNlIHNvbHV0aW9ucyBhcmUgdXNlZCBpbiBwcm9jZXNz\
ZXMgYW5kDQpidXNpbmVzcyBzaXR1YXRpb25zIGNvbW1vbiBmb3IgYWxsIGluZHVzdHJpZXMuIFRo\
ZXNlDQpzb2x1dGlvbnMgaW5jbHVkZSBwcm9kdWN0cyB0aGF0IGFyZSBkZXZlbG9wZWQgYnkgVGll\
dG8NCm9yIGEgdGhpcmQgcGFydHkgYXMgd2VsbCBhcyBzZXJ2aWNlcyByYW5naW5nIGZyb20gSVQN\
CmNvbnN1bHRpbmcgdG8gcmVsYXRlZCBpbnRlZ3JhdGlvbiwgYXBwbGljYXRpb24NCmRldmVsb3Bt\
ZW50IGFuZCBtYWludGVuYW5jZSB3b3JrLg0KbCBNYW5hZ2VkIHNlcnZpY2VzIGNvbXByaXNlcyBh\
cHBsaWNhdGlvbiBtYW5hZ2VtZW50DQppLmUuIG1haW50YWluaW5nLCBkZXZlbG9waW5nIGFuZCBl\
bmhhbmNpbmcgZXhpc3RpbmcgYXBwbGljYXRpb25zDQp1bmRlciBhIGxvbmctdGVybSBjb250cmFj\
dCwgYW5kIElDVCBpbmZyYXN0cnVjdHVyZQ0Kc2VydmljZXMgdGhhdCBlbnN1cmUgMjQvNyBvcGVy\
YXRpb25zIGZvciBjdXN0b21lcnMuDQpsIFByb2R1Y3QgZW5naW5lZXJpbmcgc29sdXRpb25zIGNv\
bXByaXNlIGRlc2lnbiwNCmRldmVsb3BtZW50IGFuZCBtYWludGVuYW5jZSBvZiBzb2Z0d2FyZSBm\
b3Igb3VyDQpjdXN0b21lcnMgcHJvZHVjdHMuIE91ciBzdHJvbmcgUiZEIG9mZmVyaW5nIGNvdmVy\
cw0KdGVsZWNvbSBuZXR3b3JrcywgbW9iaWxlIGRldmljZXMgYXMgd2VsbCBhcyBhdXRvbW90aXZl\
DQphbmQgaW5kdXN0cmlhbCBSJkQgYXJlYXMu";

const char* t2="QSBsZWFkaW5nIHNlcnZpY2UgaW50ZWdyYXRvciBjcmVhdGluZyB0aGUgYmVzdA0Kc2VydmljZSBl\
eHBlcmllbmNlIGluIElUDQpEZW1hbmQgZm9yIHNlcnZpY2VzIHRoYXQgYXJlIGF2YWlsYWJsZSBv\
biBhIGNvbnRpbnVvdXMgYmFzaXMNCmFuZCBhcmUgZWFzeSB0byB1c2Ugd2l0aG91dCB0aW1lIG9y\
IHBsYWNlIHJlc3RyaWN0aW9ucw0KY29udGludWVzIHRvIHJpc2UuIEhvd2V2ZXIsIHRoZSByZWFs\
IHN1Y2Nlc3MgY29tZXMgZnJvbQ0KdXNhYmlsaXR5LCBleGNpdGVtZW50IGFuZCBhIGdyZWF0IHNl\
cnZpY2UgZXhwZXJpZW5jZS4gTmV3DQpzZXJ2aWNlcywgZS5nLiBtb2JpbGUgZW50ZXJwcmlzZSBz\
b2x1dGlvbnMsIGFyZSBrZXkgc291cmNlcyBmb3Igb3VyDQpmdXR1cmUgZ3Jvd3RoLiBFdmVyeXRo\
aW5nIGdvZXMgbW9iaWxlIQ0KSVQgaXMgaW5jcmVhc2luZ2x5IHBhY2thZ2VkIGFuZCBjb25zdW1l\
ZCBhcyBhIHNlcnZpY2UuIE91cg0Kc3RyYXRlZ3kgZHJpdmVzIGZvciBoaWdoZXIgZGlmZmVyZW50\
aWF0aW9uIGFuZCBzcGVjaWFsaXphdGlvbiBhbmQNCmdvaW5nIGZvcndhcmQsIG1vcmUgZm9jdXMg\
aXMgcGxhY2VkIG9uIHByb2R1Y3RpemluZyBvdXIgaGlnaA0KdmFsdWUgYWRkaW5nIHNlcnZpY2Vz\
IGFuZCBvZmZlcmluZ3MuDQpUaWV0b3MgdW5pcXVlIHZhbHVlIHByb3Bvc2l0aW9uIGRyaXZlcyBn\
cm93dGggYW5kDQpwcm9maXRhYmlsaXR5DQpJbiB0b2RheXMgY29tcGV0aXRpdmUgbGFuZHNjYXBl\
LCBpdCBpcyBkaWZmaWN1bHQgdG8gYmVhdCB0aGUNCmNvbXBldGl0aW9uIG9uIHByaWNlIG9yIHB1\
cmUgcGVyZm9ybWFuY2UuIFdlIGhhdmUgY2hvc2VuIHRvDQpkaWZmZXJlbnRpYXRlIG91cnNlbHZl\
cyBmcm9tIHRoZSBjb21wZXRpdG9ycyB0aHJvdWdoIHN1cGVyaW9yDQpjdXN0b21lciBjZW50cmlj\
aXR5LiBXZSBzZWVrIHRvIG1lZXQgb3VyIGN1c3RvbWVycyBidXNpbmVzcw0KY2hhbGxlbmdlcyB3\
aXRoIG91ciBzcGVjaWFsaXplZCBzZXJ2aWNlcy4NCldpdGggb3VyIHVuaXF1ZSB2YWx1ZSBwcm9w\
b3NpdGlvbiwgd2UgaGVscCBvdXIgY3VzdG9tZXJzDQp0byBncm93IGFuZCBpbXByb3ZlIHByb2R1\
Y3Rpdml0eS4gU3VwcG9ydGluZyBjdXN0b21lcnMgd2l0aA0KdGhlIHJlbGF0ZWQgYnVzaW5lc3Mg\
dHJhbnNmb3JtYXRpb24gaXMgb25lIG9mIG91ciBjb3JlDQpjb21wZXRlbmNlcy4NClRoZSBzZWN0\
b3JzIHdlIGNvdmVyDQpUZWxlY29tIGFuZCBNZWRpYQ0KRmluYW5jZSBhbmQNCkluZHVzdHJ5IHNl\
Y3RvcnMuDQpJbmR1c3RyeSBzZWN0b3JzIGluY2x1ZGUNCi0gQXV0b21vdGl2ZQ0KLSBFbmVyZ3kg\
KEVuZXJneSB1dGlsaXRpZXMgJiBPaWwgYW5kIGdhcykNCi0gSGVhbHRoY2FyZSBhbmQgd2VsZmFy\
ZQ0KLSBNYW51ZmFjdHVyaW5nDQotIExvZ2lzdGljcw0KLSBQdWJsaWMNCi0gUmV0YWlsLg0KVGll\
dG8gYWltcyB0byBiZSBhIG1hcmtldCBsZWFkZXIgaW4gSVQgc2VydmljZXMgaW4NCk5vcnRoLUVh\
c3QgRXVyb3BlLCBhbmQgZXhwYW5kIG9wZXJhdGlvbnMgaW4gbmV3IG1hcmtldHMNCnN1Y2ggYXMg\
UnVzc2lhIGFuZCBQb2xhbmQuDQpPcGVyYXRpbmcgY291bnRyaWVzOiBBdXN0cmlhLCBHZXJtYW55\
LCBQb2xhbmQsIEJlbGFydXMsIEluZGlhLCBSdXNzaWEsDQpCZWxnaXVtLCBJbmRvbmVzaWEsIFNp\
bmdhcG9yZSwgQ2FuYWRhLCBJdGFseSwgU3BhaW4sIENoaW5hLCBMYXR2aWEsIFN3ZWRlbiwgQ3pl\
Y2ggUmVwdWJsaWMsIExpdGh1YW5pYSwgVWtyYWluZSwgRGVubWFyaywgTWFsYXlzaWEsIFVuaXRl\
ZCBLaW5nZG9tLCBFc3RvbmlhLCBOZXRoZXJsYW5kcywgVVNBLCBGaW5sYW5kLCBOb3J3YXksIEZy\
YW5jZS4=";
printf("%d", allcommon(t1,t2));
	return 0;
}
