input=<<EOM
wnwjfznwtdpyjsgnjctuwcnjcmltrr
abrfxjlrminpgpdqamzlejbqbpwkwu
iamxtlpgrkepvatjqernodzyfajqqc
vwrplefmvyjaxgmzffehpkkzlabdfs
lubcmjxhqnyfbggqqyezdrrmepgdxy
tfuhzgwxckkbnfbxqlknkskmykbatp
cbpoewhgmrrryuqhrwettutvfgmadb
chvowthqjoclzlntlckwkvebcbiazw
exuelwjpzunxvkbcrxzhzcphqtjpck
tsamxawsmbysxurfbgbyjiluzkattv
aullubmyzsyxcujqrepftsaivrdrhn
guqfqozvbwpvrbtafpjqjjqdswgbui
fvriwvnzavfmdvrggsqwhccztkzgcv
wzfdlrkpkeczwcrwynzqvrjfvdxqsx
smlwbugaitzkmfrubtayaxyjxtvbss
jbnzieewdhgxozbujbgxgodtdhabsb
pdxvekfbfwzdtcgyltibkgwalpcvph
vnrlguacvfsnlnwfayiqgxvvyggbjs
cmclznhwslbnmgyjiyifazihkanxbk
zmxqcugiyedjsdpedxqzxpeqhullsq
kjlblbrmjpwawzfmrpnixbuagdqpqe
ilfojkjojqlyovkmimpoeuppgehrzx
cwngyktfmxnkxktfbqazhlkubpkbks
iyrsjhdcjxdylzdswfmtlqsxkxhuwx
ayhbmvxpwgrcibonvlqskslaopiorj
sdcxjzehullxudqpqsmyzqxeqeipgd
tvujrycdvowqcbetzfmotuindzmhwo
efmrnqvoyjatpdapictglzqaxeqjrk
vxefloeoeihavcctnhluldhltxwunt
jrnnhtvflhjxdhqwnanaqolbqzvbcd
ulenjzngttgnvqpzkzihovnpzasfyf
bmlvzydmemqpmmqennvaybtrevfqnc
duqeiottbxebtznflpbbfofkzwrlgi
oahtvwumpgtmdqhwytrfrbubceergr
zngnnzvgsiptnyfeuhapzvkzjloftq
vtzmlvymecvqmmrnqeypmdfbqanbne
mulhkelxeatgqxfemrntnpaqnyzlet
hzclbyfzqaxqaovcvjcbgzrhmlpwhy
dqljywdyjudytsuvogkigkubqsfoku
xivjfuavhmmagvmqdavmhmzesaopkt
hnewmdjbhwccsuokvkwyoyalfkbmcv
cbhjzvrtwzyutwvomotfdqucmedion
pqgijkxzjuoplofooepmrhjyivklme
ohawmsjtpxopgjoqfggjgcuisxdqyp
cdkxkdroldsnsclpgbehkvdkiqqhdf
fdvsscqnkcfwgjudsvabhwycjvmjns
ccwlbtchklkvoeotwavzichlwjznbq
rhdixxyjruocovptmfcmuwkiufwxys
hzhxzxejuccrekcpxunpztjkqlwbvp
ybkjwuvspygauntjzcceqbscmiuukl
yzhporvmmuapgknvzcoppriktstmeg
rlxlptcmfjbdrysrvqnuuzsahyaieu
pjnctvujccwiqmuseagublzkbkuysy
wlcsvgjnfvsaynnqgxfagvulrivybg
pigjctnjmgbfaekswoaeibgdpxapvm
piifqthtvjynejkeiatczqzfnjcexf
zsvivrckmkpnygpztremaugmopopht
pooqftqigxupwjxgcgpdayjgsmhjos
szgiuwvvjpqpaqdqoqrfjbfgbjwutb
vxsoabngsrvcioarlhjomiwlbpykqp
EOM
#puts input
a=input.split("\n").collect!{|w| w.split('').sort.join('')}.sort
puts a

ans=a.uniq.inject([]){|r, i| r << { :error => i, :count => a.select{ |b| b == i }.size } }
puts ans.count{|h| h[:count]==2}